FROM almalinux:9
ENV course="devops with AWS" \
    learner="gowtham" \
    duration="120 hrs"
# here username is key, some_user is value
ARG USERANAME=Gowtham521
RUN echo "Hello USER: ${USERANAME}" 
CMD ["sleep","100"]